package Practice.Quiz.Quiz3.Exceptions;

public class Test28 {
    public static void main(String[] args) {
//        try {
//            throw new Exception("Checked");
//        } catch (RuntimeException e) {
//            System.out.println("Caught Runtime");
//        } // compile time error
    }
}
